---
title: "Time Series for Ecologists and Climatologists: course timetable"
author: "Andrew Parnell and Doug McNeall"
date: "May 2016"
output: html_document
---

Module pre-requisites can be found [here](https://rawgit.com/andrewcparnell/tsme_course/master/Prerequisites.html). All the raw files and code can be found [here](https://github.com/andrewcparnell/tsme_course). Click 'Download ZIP' near the top right if you want offline versions of everything. A pre-course questionnaire is avialable [here](http://goo.gl/forms/uKokzhP39E).

## Tuesday 10th May

Time  | Class
------------- | ----------------------------------------------------
9:15-10:00 | Time series analysis in climatology and ecology: some examples and general goals (DM) [Module 1](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_1_examples_goals/module_1_examples_goals.html)
10:00-10:45 | Discussion and coffee 
10:45-11:30 | An introduction to Bayesian statistics (AP) [Module 2](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_2_intro_bayes/module_2_intro_Bayes.html)
11:30-12:00 | Discussion and break 
12:00-12:45 | The JAGS software with simple examples (AP) [Module 3](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_3_JAGS/module_JAGS.html)
12:45-14:00 | Lunch
14:00-15:30 | Practical: Revision of R and introduction to JAGS (DM) [Practical 1](https://rawgit.com/andrewcparnell/tsme_course/master/slides)
15:30-16:00 | Break 
16:00-17:00 | Discussion: Bayesian modelling.

## Wednesday 11th May

Time  | Class
------------- | ----------------------------------------------------
9:15-10:00 | AR(1) models and Random walks (DM) [Module 4](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_4_ar1_random_walks/module_4_ar1_random_walks.html)
10:00-10:45 | Discussion and coffee 
10:45-11:30 | MA and ARIMA models (AP) [Module 5](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_5_ma_and_arima/module_5_ma_and_arima.html)
11:30-12:00 | Discussion and break 
12:00-12:45 | ARIMAX, model choice, and forecasting (AP) [Module 6](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_6_arimax_model_choice_forecasting/module_6_arimax_model_choice_forecasting.html)
12:45-14:00 | Lunch 
14:00-15:30 | Practical: Fitting ARIMA models in JAGS (DM) [Practical 2](https://rawgit.com/andrewcparnell/tsme_course/master/slides)
15:30-16:00 | Break
16:00-17:30 | Discussion: Advantages and disadvantages of ARIMA modelling

## Thursday 12th May

Time  | Class
------------- | ----------------------------------------------------
9:15-10:00 | Models with changing variance and seasonality (AP) [Module 7](https://rawgit.com/andrewcparnell/tsme_course/master/slides/mod_7_garch_svms_seasonal/module_7_garch_svms_seasonal.html)
10:00-10:45 | Discussion and coffee 
10:45-11:30 | Gaussian processes for time series (DM) [Module 8](https://rawgit.com/andrewcparnell/tsme_course/master/slides)
11:30-12:00 | Break 
12:00-12:45 | Fitting Gaussian processes in JAGS (DM) [Practical 3](https://rawgit.com/andrewcparnell/tsme_course/master/slides) 
12:45-14:00 | Lunch 
14:00-15:00 | Fitting Gaussian processes in JAGS (continued)
15:00 | Excursion

## Friday 13th May

Time  | Class
------------- | ----------------------------------------------------
9:15-10:00 | Models for continuous time series (AP) [Module 9](https://rawgit.com/andrewcparnell/tsme_course/master/slides)
10:00-10:45 | Discussion and coffee
10:45-11:30 | Extensions: state space models and multivariate time series (AP) [Module 10](https://rawgit.com/andrewcparnell/tsme_course/master/slides)
11:30-12:00 | Break 
12:00-12:45 | Practical 4: Bring your own data (AP and DM)
12:45-14:00 | Lunch
14:00-17:30 | Bring your own data (continued)

